### ISSUE TITLE
Sonarqube refers to undefined volume

### ISSUE THREAD

**Issue by badi-x** [abbashussainz/Docker-Compose-Project-for-CI-CD-Pipeline#1]
Hey,
When I just go as with readme, I could not run this docker-compose file. I'm using WSL2 Ubuntu with docker desktop.
docker-compose up -d
service "sonarqube" refers to undefined volume SonarQube_data: invalid compose project

**Comment by abbashussainz** [comment]
i have missed out named volumes for SonarQube, I have rectified that in lasts commit.
